#!/usr/bin/env bash

readonly RVT_SRC=$(dirname $(realpath -s "$0"))/..
readonly RVT_DST=/home/rust-verification-tools
readonly IMAGE=priyasiddharth/rvt_urchin:latest
#readonly MOUNT_PWD="type=bind,source=${PWD},target=${PWD}"
#readonly MOUNT_RVT="type=bind,source=${RVT_SRC},target=${RVT_DST}"

readonly MOUNT_PWD="${PWD}:${PWD}:rw"
readonly MOUNT_RVT="${RVT_SRC}:${RVT_DST}:rw"

# based on https://dzone.com/articles/docker-x11-client-via-ssh
readonly X11="--net=host --env=DISPLAY --volume=$HOME/.Xauthority:/home/$USER/.Xauthority:rw"

docker pull ${IMAGE}

docker run \
    -e LOCAL_USER_ID=`id -u $USER` \
    -e LOCAL_GROUP_ID=`id -g $USER` \
    --user 0:0 \
    --rm \
    -v ${MOUNT_RVT} \
    -v ${MOUNT_PWD} \
    --workdir ${PWD} \
    -it \
    ${X11}\
    ${IMAGE} env HOME=/home/creator $*

